[package]
name = "parquet-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
arrow = "56.0.0"
chrono = "0.4.41"
parquet = "56.0.0"
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.9.2"
